export const countries = [
  // DACH — immer oben
  { code: "DE", name: "Deutschland" },
  { code: "AT", name: "Österreich" },
  { code: "CH", name: "Schweiz" },
  // Europa alphabetisch
  { code: "AL", name: "Albanien" },
  { code: "BE", name: "Belgien" },
  { code: "BA", name: "Bosnien und Herzegowina" },
  { code: "BG", name: "Bulgarien" },
  { code: "DK", name: "Dänemark" },
  { code: "EE", name: "Estland" },
  { code: "FI", name: "Finnland" },
  { code: "FR", name: "Frankreich" },
  { code: "GR", name: "Griechenland" },
  { code: "GB", name: "Großbritannien" },
  { code: "IE", name: "Irland" },
  { code: "IS", name: "Island" },
  { code: "IT", name: "Italien" },
  { code: "XK", name: "Kosovo" },
  { code: "HR", name: "Kroatien" },
  { code: "LV", name: "Lettland" },
  { code: "LI", name: "Liechtenstein" },
  { code: "LT", name: "Litauen" },
  { code: "LU", name: "Luxemburg" },
  { code: "MT", name: "Malta" },
  { code: "MD", name: "Moldau" },
  { code: "ME", name: "Montenegro" },
  { code: "NL", name: "Niederlande" },
  { code: "MK", name: "Nordmazedonien" },
  { code: "NO", name: "Norwegen" },
  { code: "PL", name: "Polen" },
  { code: "PT", name: "Portugal" },
  { code: "RO", name: "Rumänien" },
  { code: "RU", name: "Russland" },
  { code: "SE", name: "Schweden" },
  { code: "RS", name: "Serbien" },
  { code: "SK", name: "Slowakei" },
  { code: "SI", name: "Slowenien" },
  { code: "ES", name: "Spanien" },
  { code: "CZ", name: "Tschechien" },
  { code: "TR", name: "Türkei" },
  { code: "UA", name: "Ukraine" },
  { code: "HU", name: "Ungarn" },
  { code: "BY", name: "Weißrussland" },
  { code: "CY", name: "Zypern" },
  // Amerika
  { code: "AR", name: "Argentinien" },
  { code: "BR", name: "Brasilien" },
  { code: "CL", name: "Chile" },
  { code: "CA", name: "Kanada" },
  { code: "CO", name: "Kolumbien" },
  { code: "MX", name: "Mexiko" },
  { code: "US", name: "USA" },
  // Asien / Pazifik
  { code: "AE", name: "Arabische Emirate" },
  { code: "AU", name: "Australien" },
  { code: "CN", name: "China" },
  { code: "IN", name: "Indien" },
  { code: "ID", name: "Indonesien" },
  { code: "IL", name: "Israel" },
  { code: "JP", name: "Japan" },
  { code: "KZ", name: "Kasachstan" },
  { code: "MY", name: "Malaysia" },
  { code: "NZ", name: "Neuseeland" },
  { code: "PH", name: "Philippinen" },
  { code: "SA", name: "Saudi-Arabien" },
  { code: "SG", name: "Singapur" },
  { code: "KR", name: "Südkorea" },
  { code: "TW", name: "Taiwan" },
  { code: "TH", name: "Thailand" },
  { code: "VN", name: "Vietnam" },
  { code: "HK", name: "Hongkong" },
  // Afrika
  { code: "DZ", name: "Algerien" },
  { code: "EG", name: "Ägypten" },
  { code: "KE", name: "Kenia" },
  { code: "MA", name: "Marokko" },
  { code: "NG", name: "Nigeria" },
  { code: "ZA", name: "Südafrika" },
];
